substitutions:
  name: "esp8266-dht11"
  friendly_name: "ESP8266 DHT11 Sensor"
  device_description: "ESP8266 NodeMCU with DHT-11 Temperature and Humidity Sensor"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  comment: "${device_description}"
  platform: ESP8266
  board: nodemcuv2

# Enable logging
logger:
  level: DEBUG
  baud_rate: 115200  # Serial monitor baud rate
  hardware_uart: UART0  # Use hardware UART for serial output

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

# Enable Over-The-Air updates
ota:
  - platform: esphome
    password: !secret ota_password

# WiFi connection
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret wifi_ap_password

# Captive portal for WiFi configuration
captive_portal:

# Web server for debugging
web_server:
  port: 80

# DHT-11 Temperature and Humidity Sensor
# Connected to GPIO4 (D2 pin on NodeMCU)
sensor:
  - platform: dht
    pin: GPIO4
    model: DHT11
    temperature:
      name: "${friendly_name} Temperature"
      id: dht_temperature
      accuracy_decimals: 1
      filters:
        - offset: 0.0  # Calibration offset if needed
    humidity:
      name: "${friendly_name} Humidity"
      id: dht_humidity
      accuracy_decimals: 0
      filters:
        - offset: 0.0  # Calibration offset if needed
    update_interval: 30s  # Update every 30 seconds

  # WiFi Signal Strength
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s

  # Uptime Sensor
  - platform: uptime
    name: "${friendly_name} Uptime"
    update_interval: 60s

# Text Sensors
text_sensor:
  # ESP8266 Info
  - platform: version
    name: "${friendly_name} ESPHome Version"
    
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
    ssid:
      name: "${friendly_name} SSID"
    mac_address:
      name: "${friendly_name} MAC Address"

# Binary Sensors
binary_sensor:
  # Status sensor
  - platform: status
    name: "${friendly_name} Status"

# Restart button
button:
  - platform: restart
    name: "${friendly_name} Restart"

# Switch for toggling updates (optional)
switch:
  - platform: template
    name: "${friendly_name} Auto Update"
    id: auto_update_switch
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
