substitutions:
  name: "phijo-smart-device"
  friendly_name: "Phijo Smart"
  device_description: "Smart Controller"
  project_name: "Guition.ESP32_S3_4848S040"
  project_version: "09.07.26.1"
  wifi_ssid: "AlfaobeiroGuest"
  wifi_password: "Vale2020"

  log_main: "DEBUG"
  log_boot: "DEBUG"
  log_light_time: "DEBUG"
  log_irrigation: "DEBUG"
  log_automation: "DEBUG"
  log_pump: "DEBUG"
  log_weather: "DEBUG"
  log_ui: "DEBUG"
  log_touch: "DEBUG"
  log_switch_state: "DEBUG"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"

  project:
    name: "${project_name}"
    version: "${project_version}"

  platformio_options:
    build_flags:
      - -DCONFIG_ESP_CONSOLE_UART_DEFAULT=y
    build_unflags:
      - "-f"
      - "-shared"

  on_boot:
    priority: 600
    then:
      - lambda: |-
          ESP_LOGI("BOOT", "====================================");
          ESP_LOGI("BOOT", "Device: ${friendly_name}");
          ESP_LOGI("BOOT", "Project: ${project_name}");
          ESP_LOGI("BOOT", "Version: ${project_version}");
          ESP_LOGI("BOOT", "Boot complete");
          ESP_LOGI("BOOT", "====================================");

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf

##########################################################
# NETWORK
##########################################################

wifi:
  ssid: "${wifi_ssid}"
  password: "${wifi_password}"

  ap:
    ssid: "${friendly_name} Fallback"
    password: "12345678"

captive_portal:

##########################################################
# OTA
##########################################################

ota:
  platform: esphome
 

##########################################################
# WEB SERVER
##########################################################

web_server:
  port: 80
  version: 3
  include_internal: true
  log: true

##########################################################
# API
##########################################################

api:

##########################################################
# LOGGER
##########################################################

logger:
   

##########################################################
# MAIN LOOP
##########################################################

interval:
  - interval: 1s
    then:
      - lambda: |-
          static int counter = 0;
          counter++;
          ESP_LOGD("COUNTER", "Count: %d", counter);
  - interval: 2s
    then:
      - logger.log:
          tag: TEST
          level: INFO
          format: "Counter alive"
##########################################################
# TEST SWITCH
##########################################################

switch:
  - platform: template
    name: "Debug Switch"

    turn_on_action:
      - lambda: |-
          ESP_LOGD("DEBUG_SWITCH", "Switch turned ON");

    turn_off_action:
      - lambda: |-
          ESP_LOGD("DEBUG_SWITCH", "Switch turned OFF");