# Camera GPIOs: 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 16, 17, 18

# Other GPIOs: 3 (LDR), 19 (IR on), 20 (IR off), 21 (Flashlight), 14 (Presence)

# Conflicts: None—all assigned GPIOs are unique and avoid the camera pins.

#esp32cam.yaml
esphome:
  name: esp32-camera-4
  friendly_name: ESP32-CAMERA-4

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

logger:

api:
  encryption:
    key: "9HLR1P/vVsbBBautrFIB6B2M/YzNR2av+Qn5NnkTI4g="

ota:
  - platform: esphome
    password: "4498c0576bfad57bb2221157292dcb55"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Esp32-Camera-4 Fallback Hotspot"
    password: "yOfkM4dy34Lj"

captive_portal:

# Camera configuration
esp32_camera:
  external_clock:
    pin: GPIO15
    frequency: 20MHz
  i2c_pins:
    sda: GPIO4
    scl: GPIO5
  data_pins: [GPIO11, GPIO9, GPIO8, GPIO10, GPIO12, GPIO18, GPIO17, GPIO16]
  vsync_pin: GPIO6
  href_pin: GPIO7
  pixel_clock_pin: GPIO13
  name: My ESP32-S3-EYE-CAM

# Flashlight LED
output:
  - platform: gpio
    pin: GPIO21
    id: gpio_21

light:
  - platform: binary
    output: gpio_21
    name: Flashlight

# IR Cut Control
switch:
  - platform: gpio
    pin: GPIO19
    id: ir_on
    restore_mode: ALWAYS_OFF
  - platform: gpio
    pin: GPIO20
    id: ir_off
    restore_mode: ALWAYS_OFF

# LDR Sensor
sensor:
  - platform: adc
    pin: GPIO2
    name: "Ambient Light Level"
    update_interval: 5s
    filters:
      - calibrate_linear:
          - 0.0 -> 100.0
          - 3.3 -> 0.0
    unit_of_measurement: "%"
    device_class: illuminance
    id: ldr_sensor
    on_value:
      then:
        - if:
            condition:
              lambda: 'return (id(ldr_sensor).state < 30);'
            then:
              - switch.turn_on: ir_off
              - switch.turn_off: ir_on
        - if:
            condition:
              lambda: 'return (id(ldr_sensor).state >= 30);'
            then:
              - switch.turn_on: ir_on
              - switch.turn_off: ir_off

# Presence Sensor
binary_sensor:
  - platform: gpio
    pin: GPIO14
    name: "LD2410 Presence Trigger"
    device_class: motion