esphome:
  name: totalsense-c3-ld2450
  friendly_name: TOTALSENSE-C3-LD2450



external_components:
  - source:
      type: git
      url: https://github.com/smart-life-tech/esphome-ld2450
      ref: master
    components: [ ld2450 ]

esp32:
  #board: esp32-c3-devkitm-1
  #board: esp32dev
  board: seeed_xiao_esp32c3
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG


# Enable Home Assistant API
api:
  encryption:
    key: "Gvh95r+mEMBnRqAsPSDErYxl4K6wSFegCHzNMnORo68="

ota:
  - platform: esphome
    password: "cf51b5565f8fc607aff12f6a2ab55d98"

wifi:
  ssid: "JEREMY"
  password: "605506Jdb"

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Totalsense-C3-Ld2450"
    password: "0TvgXQwX6lmA"

captive_portal:

web_server:
  port: 80

uart:
  id: uart_bus
  tx_pin: 
    number: GPIO21
  rx_pin: 
    number: GPIO20
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2450:
  uart_id: uart_bus
  update_interval: 5s
  invert_y: false
  invert_x: false
binary_sensor:
  - platform: ld2450
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
    presence_regions:
      - name: "Custom Presence Region 0"
        region_id: presence_region_0
  - platform: gpio
    pin: GPIO4
    name: "PIR Sensor"
    device_class: motion
    on_press:
      - light.turn_on:
          id: living_room_leds
    on_release:
      - light.turn_off:
          id: living_room_leds

text_sensor:
  - platform: ld2450
    version:
      name: "FW"
    mac_address:
      name: "MAC address"

button:
  - platform: restart
    name: "ESP Restart"
  - platform: ld2450
    factory_reset:
      name: "Factory reset"
    reboot:
      name: "Reboot"

switch:
  - platform: ld2450
    single_target:
      name: "Single target"
    bluetooth:
      name: "Bluetooth"

number:
- platform: ld2450
  rotate:
    restore_value: true
    initial_value: 0
    name: "Rotate angle"
  presence_timeout:
    name: "Presence timeout"
  presence_regions:
    - x0: 100
      y0: 100
      x1: 200
      y1: 200
      id: presence_region_0
  entry_points:
    - x: 0
      y: 0
  region_0:
    x0:
      name: R0X0
    y0:
      name: R0Y0
    x1:
      name: R0X1
    y1:
      name: R0Y1

  region_1:
    x0:
      name: R1X0
    y0:
      name: R1Y0
    x1:
      name: R1X1
    y1:
      name: R1Y1

  region_2:
    x0:
      name: R2X0
    y0:
      name: R2Y0
    x1:
      name: R2X1
    y1:
      name: R2Y1

select:
  - platform: ld2450
    baud_rate:
      name: "Baud rate"
    regions_type:
      name: "Regions type"

sensor:
- platform: ld2450
  target_count:
    name: Target count

  person_0:
    position_x:
      name: "P0X"  

    position_y:
      name: "P0Y"  

    speed:
      name: "S0"  

    resolution:
      name: "R0"  

  person_1:
    position_x:
      name: "P1X"  

    position_y:
      name: "P1Y"  

    speed:
      name: "S1"  

    resolution:
      name: "R1"  

  person_2:
    position_x:
      name: "P2X"  

    position_y:
      name: "P2Y"  

    speed:
      name: "S2"  

    resolution:
      name: "R2"

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO18
    num_leds: 150
    rgb_order: GRB
    name: "Living Room LEDs"
    id: living_room_leds